version: '3.8'

services:
  cardano-devnet:
    image: cardano-devnet
    container_name: cardano-devnet
    environment:
      # Check .env file for possible values
      - EPOCH_LENGTH=600
    volumes:
      - ./devnet-data:/opt/cardano-node/devnet
